/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uw_Taggerflow */

#ifndef _Included_edu_uw_Taggerflow
#define _Included_edu_uw_Taggerflow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uw_Taggerflow
 * Method:    close
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_edu_uw_Taggerflow_close
  (JNIEnv *, jclass, jlong);

/*
 * Class:     edu_uw_Taggerflow
 * Method:    initialize
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_edu_uw_Taggerflow_initialize
  (JNIEnv *, jclass, jbyteArray);

/*
 * Class:     edu_uw_Taggerflow
 * Method:    queueInput
 * Signature: ([BJ)V
 */
JNIEXPORT void JNICALL Java_edu_uw_Taggerflow_queueInput
  (JNIEnv *, jclass, jbyteArray, jlong);

/*
 * Class:     edu_uw_Taggerflow
 * Method:    predictRemainingFromInput
 * Signature: (J)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_uw_Taggerflow_predictRemainingFromInput
  (JNIEnv *, jclass, jlong);

/*
 * Class:     edu_uw_Taggerflow
 * Method:    queueFile
 * Signature: (Ljava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_edu_uw_Taggerflow_queueFile
  (JNIEnv *, jclass, jstring, jlong);

/*
 * Class:     edu_uw_Taggerflow
 * Method:    predictRemainingFromFile
 * Signature: (IJ)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_uw_Taggerflow_predictRemainingFromFile
  (JNIEnv *, jclass, jint, jlong);

#ifdef __cplusplus
}
#endif
#endif
