/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_uw_Taggerflow */

#ifndef _Included_edu_uw_Taggerflow
#define _Included_edu_uw_Taggerflow
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_uw_Taggerflow
 * Method:    closeTensorflow
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_edu_uw_Taggerflow_closeTensorflow
  (JNIEnv *, jobject);

/*
 * Class:     edu_uw_Taggerflow
 * Method:    initializeTensorflow
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_edu_uw_Taggerflow_initializeTensorflow
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     edu_uw_Taggerflow
 * Method:    predictPacked
 * Signature: ([B)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_uw_Taggerflow_predictPacked___3B
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     edu_uw_Taggerflow
 * Method:    predictPacked
 * Signature: (Ljava/lang/String;I)[B
 */
JNIEXPORT jbyteArray JNICALL Java_edu_uw_Taggerflow_predictPacked__Ljava_lang_String_2I
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
